name: Process WPT Results

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUSTDOCFLAGS: "-D warnings"
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: "sparse"

jobs:
  wpt:
    name: "Fetch results"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List results
        run: |
          curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/dioxuslabs/blitz/actions/artifacts?page=1"