name: Process WPT Results

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUSTDOCFLAGS: "-D warnings"
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: "sparse"

jobs:
  wpt:
    name: "Import WPT Results"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Set git credentials
        run: |
          git config user.name blitz-ci
          git config user.email ci@blitz.is
      - name: Process results
        run: cargo run -rp process
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        run: git push
      # - name: Compress report (zstd)
      #   run: zstd -22 --ultra -o ./wpt/output/wptreport.json.zst ./wpt/output/wptreport.json
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: wpt-report.json.zst
      #     path: ./wpt/output/wptreport.json.zst
      #     compression: 0 # We are already using zstd compression
