name: Process WPT Results

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUSTDOCFLAGS: "-D warnings"
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: "sparse"

jobs:
  wpt:
    name: "Import WPT Results"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout blitz (for commit metadata)
        uses: actions/checkout@v4
        with:
          repository: DioxusLabs/blitz
          path: blitz-checkout
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - name: Set git credentials
        run: |
          git config user.name blitz-ci
          git config user.email ci@blitz.is
      - name: Process results
        run: cargo run -rp process
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BLITZ_REPO: ${{ github.workspace }}/blitz-checkout
      - name: Push changes
        run: git push

  publish:
    name: "Publish summary data to GitHub Pages"
    needs: wpt
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Build pages site
        run: |
          mkdir -p _site
          cp -r summary _site/summary
          tar -cf - summary | zstd -19 -o _site/summary.tar.zst
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      - id: deployment
        uses: actions/deploy-pages@v4
